project:
  type: website

website:
  title: "blog_github"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/e-riveras
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css



